# Streamlit Cloud Secrets Template
# Copy this file to .streamlit/secrets.toml for local development
# For Streamlit Cloud deployment, add these values in the web interface under Settings → Secrets

# OpenAI API Configuration
OPENAI_API_KEY = "sk-proj-your-openai-api-key-here"

# Snowflake Database Configuration
SNOWFLAKE_USER = "your_snowflake_username"
SNOWFLAKE_PASSWORD = "your_snowflake_password"
SNOWFLAKE_ACCOUNT = "your_snowflake_account_identifier"
SNOWFLAKE_WAREHOUSE = "your_warehouse_name"
SNOWFLAKE_DATABASE = "userprofiles"
SNOWFLAKE_SCHEMA = "public"

# Optional: Heroku App Name (if using Heroku deployment)
HEROKU_APP_NAME = "your-app-name" 